### ISSUE TITLE
We can remove the library of Action scheduler from our plugin

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#606]
**Describe the bug**
We can remove the library of Action scheduler from our plugin

As WooCommerce 4.0 beta 1 is available now and they mentioned that "We don’t expect the update to cause a lot of problems, as the only truly breaking change is including Action Scheduler 3.0 which already runs on more than 10,000 sites with WooCommerce Subscriptions."

**Comment by pinalj** [comment]
We will be including the library from WC. So the library folder will no longer be a part of our plugin. 

Since the library was included as a part of WC in version 3.5.0, if a site is using an older version, the library inclusion from WC will fail. In such a scenario, our plugin will add an admin notice indicating that we're unable to find the library and they need to ensure that they are using a later version of WC. If not, then no automated emails will be sent.
