### ISSUE TITLE
The price is showing 0 for the visitor carts.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#652]
**Describe the bug**
Price is showing 0 for visitor carts on a client site. For guest user carts, the price is showing correctly. 

**To Reproduce**
1. Abandon a visitor cart on his site.
2. Price 0 is displaying only for visitor carts.

Note: I am able to replicate this issue on a client site. I tried to replicate it at our end but I am unable to replicate it.

**Screenshots or Video**
https://www.screencast.com/t/xqZmvqMLb7

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

https://tychesoftwares.freshdesk.com/a/tickets/19316

**Comment by pinalj** [comment]
The issue is not from our plugin. The cart details are not being logged correctly in WC session. This might be due to a conflict with any plugin or theme. Since our plugin does not find the cart totals etc. in WC session, the same is not captured correctly in our plugin record and hence not displayed.

**Comment by pinalj** [comment]
Visitor carts are being tracked fine.
