### ISSUE TITLE
Checkout link redirect me on cart page instead of My Account page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#917]
**Describe the bug**
Checkout link redirect me on cart page instead of My Account page.

**To Reproduce**
1. Take 5.15.2 copy 
2. Abandoned some carts as guest users + Logged in users 
3. Reminder email received and cliked on checkout link, it's redirects me on cart page which is correct 
4. Upload the latest master copy 
5. Again clicked on checkout link, the plugin redirects me on cart page instead of My account page. 

**Expected behavior**
Checkout link should redirect me on My Account page.

**Comment by pinalj** [comment]
1. The issue occurs because the default value passed to the `get_option()` function is incorrect. Instances found:

https://github.com/TycheSoftwares/woocommerce-abandoned-cart/blob/773bb2f0cb68c1c436dc745f59c494afee6f037a/woocommerce-ac.php#L284
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/blob/773bb2f0cb68c1c436dc745f59c494afee6f037a/woocommerce-ac.php#L1999

2. The plugin version has not been updated. This results in the update code not being executed.

3. Also, it seems the code to set the auto login setting default value to off/blanks for fresh installations is missing.
